### ISSUE TITLE
Secure mode

### ISSUE THREAD

**Issue by cprussin** [levanto-financial/ember-intercom-io#15]
Does this mixin support any way of enabling intercom's [secure mode](https://app.intercom.io/a/apps/pvykiay8/guide/web_integration/web_integration_secure_mode)?

Thanks!

**Comment by mike-north** [comment]
There's no reason why this addon wouldn't support secure mode. You are responsible for generating a HMAC token on your own back-end, and passing it to Intercom as you initialize it through the ember service

**Comment by mbbertino** [comment]
@mike-north I created #26 to solve this issue when you get a chance, would love a merge.

**Comment by mbbertino** [comment]
This isn't an issue anymore thanks to https://github.com/levanto-financial/ember-intercom-io/pull/26

@cprussin you want to close the issue?

**Comment by cprussin** [comment]
Closing.  Thanks all!
