### ISSUE TITLE
Initializer not creating Intercom script on page load

### ISSUE THREAD

**Issue by ianpetzer** [levanto-financial/ember-intercom-io#4]
Hi there,

This looks like an awesome addon but I'm having an issue in getting to to work.

The ember-intercom initializer kicks in during app boot and the function to insert the intercom script tag is defined and attached to the window load event however it never triggers.

I've copied and pasted the code snippet that does this into my app.js file where it works beautifully, and included as snippet below.

Is it possible that the load event is being fired before the initializer is run?

      var w = window;
      var d = document;
      var i = function() {
        i.c(arguments)
      };
      i.q = [];
      i.c = function(args) {
        i.q.push(args)
      };
      w.Intercom = i;

      function l() {
        var s = d.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = `https://widget.intercom.io/widget/${Ember.get(config, 'intercom.appId')}`;
        var x = d.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
      }
      if (w.attachEvent) {
        w.attachEvent('onload', l);
      } else {
        w.addEventListener('load', l, false);
      }

**Comment by bbjunaid** [comment]
Hi,

Did you figure this out? I'm getting a similar issue.

**Comment by ianpetzer** [comment]
Not yet... I jsut use the workaround described above

**Comment by ianpetzer** [comment]
Actually I've created my own instance initializer, which inserts the Intercom script

**Comment by bbjunaid** [comment]
My work around was before attaching the event listener, if document.readyState === "complete", then I directly call l(). 

Turns out in my app, the load event was already triggered by the time I wanted to insert the snippet, so I can't rely on attaching an event listener.
